FROM jordifebrer/jenkins
MAINTAINER Jordi Febrer <jordi.febrer@gmail.com>

# web server
EXPOSE 8080

# run jenkinsci server
CMD java -jar /usr/lib/jenkins/jenkins.war

# docker build -t="jordifebrer/jenkins-server" .
# docker run -d -p 8080:8080 jordifebrer/jenkins-server
